name: Scrape current + CMA & Build index

on:
  push:
    paths:
      - 'scripts/**'
      - '.github/workflows/scrape-and-index.yml'
      - 'data/**'
      - 'assets/**'
      - 'index.html'
  schedule:
    - cron: '0 4 * * 1'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          python -m pip install --upgrade pip
          python -m pip install beautifulsoup4 lxml requests

      - name: Scrape current versions + CMA table
        run: |
          python scripts/scrape_current_versions.py

      - name: Build full-text index
        run: |
          python scripts/build_index.py

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update catalogue (current + CMA) & full-text index"
          file_pattern: |
            data/a64_catalogue.json
            search_index.json
